---
Name: silverstripe-embedder
---

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - richardsjoqvist\silverstripeEmbedder\Embedder

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.silverstripeEmbedder:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "silverstripeEmbedder"